- name: Install Grafana
  hosts: osama123
  become: true
  roles:
    - atosatto.grafana 
  vars:
    grafana_version: 8.3.3 
    grafana_admin_user: admin
    grafana_admin_password: secret 
    grafana_datasources: 
      - name: Prometheus
        type: prometheus
        access: proxy
        url: 127.0.0.1:9090
        is_default: true