- name: Install prometheus
  hosts: osama123
  become: true
  roles:
    - cloudalchemy.prometheus 
  vars:
    prometheus_version: 2.32.1
    prometheus_web_listen_address: "127.0.0.1:9090" 
    prometheus_targets: 
      node:
      - targets:
        - localhost:9100
        labels:
          env: test